version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - '${MONGO_HOST}:${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongodb_data: