version: '3.9'
services:
  mongodb_service_dev:
    image: mongo:latest
    container_name: mongodb_container_dev
    restart: unless-stopped
    volumes:
      - mongodb_data_dev:/data/db
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

volumes:
  mongodb_data_dev: